use_frameworks!

platform :ios, '14.0'

target 'Home_Example' do
  pod 'Home', :path => '../'

  target 'Home_Tests' do
    inherit! :search_paths

    
  end
  
  
  pod 'CorePokeDex', :path => '../../CorePokeDex'
  pod 'CoreEntities', :path => '../../CoreEntities'


end
